# -*- coding: utf-8 -*-
"""Neftecode_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148plU4eC5Ev3W0TT03gx9zKW3jgPu8Fm
"""

# Полный пайплайн предобработки данных для МАС (АВТ -> гидроочистка -> блендинг)
# с экспортом артефактов, срезов под агентов и отчётов.

from __future__ import annotations

import json
import logging
import os
import re
import warnings
from dataclasses import dataclass, field
from difflib import get_close_matches
from pathlib import Path
from typing import Iterable, Literal

import numpy as np
import pandas as pd

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",)

# Пути
@dataclass
class Paths:
  avt_tags: Path = Path("avt_tags.csv")
  hydro_tags: Path = Path("242000_tags.csv")
  lims_xlsx: Path = Path("ЛИМСы 01.01.2023 - н.в_ (2).xlsx")
  pak_xlsx: Path = Path("Выгрузка ПАК.xlsx")
  tags_xlsx: Path = Path("Теги_хакатон.xlsx")

# Общие утилиты
_UNIT_RE = re.compile(r"\[(.*?)\]")

DT_FORMAT = "%Y-%m-%d %H:%M:%S"
DT_FALLBACK = "mixed"

def _parse_dt(series: pd.Series) -> pd.Series:
  # Парсинг дат
  with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=UserWarning)
    try:
      parsed = pd.to_datetime(series, format=DT_FORMAT, errors="coerce")
      if parsed.notna().mean() > 0.9:
        return parsed
    except (ValueError, TypeError):
      pass
    return pd.to_datetime(series, format=DT_FALLBACK, errors="coerce")

def _strip_units(name: str) -> tuple[str, str | None]:
  if not isinstance(name, str):
    return str(name), None
  m = _UNIT_RE.search(name)
  if m:
    return _UNIT_RE.sub("", name).strip(), m.group(1).strip()
  return name.strip(), None

def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
  # Заголовки в snake_case; карта единиц в df.attrs['units']
  units: dict[str, str | None] = {}
  new_cols = []
  for c in df.columns:
    base, unit = _strip_units(str(c))
    snake = re.sub(r"[^\w]+", "_", base).strip("_").lower()
    units[snake] = unit
    new_cols.append(snake)
  df = df.copy()
  df.columns = new_cols
  df.attrs["units"] = units
  return df

def to_datetime(df: pd.DataFrame, col: str | None = None,
                date_col: str | None = None) -> pd.DataFrame:
  # Колонка с датой к datetime и сортировка
  target = col or date_col or "date"
  if target not in df.columns:
    raise KeyError(f"to_datetime: колонка '{target}' не найдена."
                   f"Доступные: {list(df.columns)[:20]}...")
  df = df.copy()
  df[target] = _parse_dt(df[target])
  df = df.dropna(subset=[target]).sort_values(target).reset_index(drop=True)
  return df

def _canon(name: str) -> str:
  # Канонизация имени индикатора для сопоставления
  s = str(name).strip().lower().replace("ё", "е")
  s = re.sub(r"[^\w]+", "_", s)
  return s.strip("_")

def _norm_sheet(name: str) -> str:
  # Нормализация имени листа
  s = str(name).strip().lower().replace("ё", "е")
  s = re.sub(r"[\s_\-\(\)\[\]\.]+", "", s)
  return s

def resolve_sheet(xlsx: Path, wanted: str | list[str] | tuple[str, ...],
                  fuzzy_cutoff: float = 0.6) -> str | None:
  # Ищет лист по имени
  wanted_list = [wanted] if isinstance(wanted, str) else list(wanted)
  sheets = pd.ExcelFile(xlsx).sheet_names
  if not sheets:
    return None

  for w in wanted_list:
    if w in sheets:
      return w

  norm_map = {_norm_sheet(s): s for s in sheets}
  for w in wanted_list:
    nw = _norm_sheet(w)
    if nw in norm_map:
      return norm_map[nw]

  for w in wanted_list:
    matches = get_close_matches(_norm_sheet(w), list(norm_map.keys()),
                                n=1, cutoff=fuzzy_cutoff)
    if matches:
      return norm_map[matches[0]]

  for w in wanted_list:
    nw = _norm_sheet(w)
    for ns, orig in norm_map.items():
      if nw and (nw in ns or ns in nw):
        return orig

  return None

# Телеметрия
def load_telemetry(path: Path, date_col: str = "date") -> pd.DataFrame:
  # Загрузчик одного CSV с телеметрией
  df = pd.read_csv(path, low_memory=False)

  unnamed = [c for c in df.columns if str(c).startswith("Unnamed:")]
  df = df.drop(columns=[c for c in unnamed if c != date_col], errors="ignore")

  if date_col not in df.columns:
    chosen = None
    for c in df.columns:
      parsed = _parse_dt(df[c])
      if parsed.notna().mean() > 0.9:
        df[c] = parsed
        chosen = c
        break
    if chosen is None:
      raise ValueError(f"Не найдена колонка с датой в {path.name}. "
                       f"Колонки: {list(df.columns)[:20]}")
    date_col = chosen

  df = normalize_columns(df)
  df = to_datetime(df, date_col)

  for c in df.columns:
    if c != date_col:
      df[c] = pd.to_numeric(df[c], errors="coerce")

  df = df.rename(columns={date_col: "date"})
  log.info("Телеметрия %s: %s, диапазон %s → %s",
           path.name, df.shape, df["date"].min(), df["date"].max())
  return df

# Справочник КИП
def load_kip_map(path: Path, sheet: str = "КИП") -> pd.DataFrame:
  # Карта тегов с колонкой plant
  raw = pd.read_excel(path, sheet_name=sheet, header=0)
  cols = list(raw.columns)

  def _pair(desc_col, tag_col, plant: str):
    sub = raw[[desc_col, tag_col]].dropna()
    out = []
    for desc, tag in sub.itertuples(index=False):
      if not isinstance(tag, str) or not tag.strip():
        continue
      out.append({
          "tag": tag.strip(),
          "description": str(desc).strip(),
          "plant": plant,
      })
    return out

  records = []
  if len(cols) >= 2:
    records += _pair(cols[0], cols[1], "AVT")
  if len(cols) >= 4:
    records += _pair(cols[2], cols[3], "24-2000")

  kip = (pd.DataFrame.from_records(records).drop_duplicates(["plant", "tag"])
         .reset_index(drop=True))
  log.info("Карта КИП: %d тегов (AVT=%d, 24-2000=%d)",
           len(kip),
           int((kip["plant"] == "AVT").sum()),
           int((kip["plant"] == "24-2000").sum()))
  return kip

def tag(plant: str, name: str) -> str:
  """tag('AVT','T6') -> 'avt_T6'; tag('24-2000','T6') -> 'hyd_T6'."""
  prefix = "avt" if str(plant).upper() == "AVT" else "hyd"
  return f"{prefix}_{name}"

# ЛИМС -> long
def load_lims(path: Path, sheet: str | int = 0) -> pd.DataFrame:
  # ЛИМСы: 2 строки заголовка, далее - пары (timestamp, value)
  raw = pd.read_excel(path, sheet_name=sheet, header=None, dtype=object)
  hdr_plant = raw.iloc[0].ffill()
  hdr_ind = raw.iloc[1]
  hdr_unit = raw.iloc[2]
  body = raw.iloc[3:].reset_index(drop=True)

  records = []
  col = 0
  while col < raw.shape[1] - 1:
    plant_cell = hdr_plant.iloc[col]
    ind_cell = hdr_ind.iloc[col]
    unit_cell = hdr_unit.iloc[col]
    if pd.isna(plant_cell) or pd.isna(ind_cell):
        col += 2
        continue

    s = str(plant_cell)
    plant = re.search(r"Установка\s*'([^']+)'", s)
    point = re.search(r"Точка отбора\s*'([^']+)'", s)
    product = re.search(r"Продукт\s*'([^']+)'", s)

    rec = {
        "plant": plant.group(1).strip() if plant else None,
        "sampling_point": point.group(1).strip() if point else None,
        "product": product.group(1).strip() if product else None,
        "indicator": str(ind_cell).strip(),
        "unit": str(unit_cell).strip() if pd.notna(unit_cell) else None,
    }

    sub = pd.DataFrame({
        "timestamp": _parse_dt(body.iloc[:, col]),
        "value": pd.to_numeric(body.iloc[:, col + 1], errors="coerce"),
    }).dropna(subset=["timestamp"])
    if sub.empty:
      col += 2
      continue

    for k, v in rec.items():
      sub[k] = v
    records.append(sub)
    col += 2

  if not records:
    log.warning("ЛИМС: не удалось разобрать ни одного столбца в %s", path.name)
    return pd.DataFrame(columns=["timestamp", "plant", "sampling_point",
                                 "product", "indicator", "unit", "value"])

  long = pd.concat(records, ignore_index=True)
  long = long.dropna(subset=["value"]).sort_values("timestamp").reset_index(drop=True)
  log.info("ЛИМС: %d строк, %d уникальных индикаторов", len(long),
           long["indicator"].nunique())
  return long


# ПАК/ВАК
def load_pak(path: Path, sheet_aliases: tuple[str, ...] =
             ("ПАК", "PAK", "Поточный", "Лист1"), required: bool = False) -> pd.DataFrame:
  # Прочитывание единого листа ПАК/ВАК в long-формат
  if not path.exists():
    msg = f"Файл {path} не найден."
    if required:
      raise FileNotFoundError(msg)
    log.warning(msg)
    return pd.DataFrame(columns=["timestamp", "indicator", "value",
                                 "source_sheet"])

  sheets = pd.ExcelFile(path).sheet_names
  sheet_name = next((s for s in sheets if s in sheet_aliases), None)
  if sheet_name is None:
    sheet_name = sheets[0]
    log.info("Лист из %s не найден; использую '%s' из %s.", sheet_aliases,
             sheet_name, sheets)

  raw = pd.read_excel(path, sheet_name=sheet_name, header=None, dtype=object)
  if raw.empty:
    log.warning("Лист '%s' пуст.", sheet_name)
    return pd.DataFrame(columns=["timestamp", "indicator", "value",
                                 "source_sheet"])

  hdr = raw.iloc[0]
  body = raw.iloc[1:].reset_index(drop=True)

  records = []
  col = 0
  while col < raw.shape[1] - 1:
    desc = hdr.iloc[col]
    if pd.isna(desc):
      col += 2
      continue
    sub = pd.DataFrame({
        "timestamp": _parse_dt(body.iloc[:, col]),
        "value": pd.to_numeric(body.iloc[:, col + 1], errors="coerce"),
    }).dropna(subset=["timestamp"])
    sub["indicator"] = str(desc).strip()
    sub["source_sheet"] = sheet_name
    records.append(sub)
    col += 2

  if not records:
    log.warning("ПАК/ВАК: не удалось разобрать столбцы в %s/%s", path.name,
                sheet_name)
    return pd.DataFrame(columns=["timestamp", "indicator", "value",
                                 "source_sheet"])

  long = (pd.concat(records, ignore_index=True).sort_values("timestamp")
          .reset_index(drop=True))
  log.info("ПАК/ВАК (%s/%s): %d строк, %d уникальных индикаторов", path.name,
           sheet_name, len(long), long["indicator"].nunique())
  return long


def _read_reference_list(tags_xlsx: Path, sheet: str) -> set[str]:
  # Лист справочника -> множество канонизированных имен
  if sheet not in pd.ExcelFile(tags_xlsx).sheet_names:
    log.warning("Лист '%s' отсутствует в %s", sheet, tags_xlsx.name)
    return set()
  d = pd.read_excel(tags_xlsx, sheet_name=sheet, header=None, dtype=object)
  vals: set[str] = set()
  for v in d.values.ravel():
    if isinstance(v, str) and v.strip():
      vals.add(_canon(v))
  return vals


def split_pak_vak(long_df: pd.DataFrame, tags_xlsx: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
  # Разделяем единый long на ПАК и ВАК по справочнику
  empty_cols = ["timestamp", "indicator", "value", "source_sheet"]
  if long_df is None or long_df.empty:
    return pd.DataFrame(columns=empty_cols), pd.DataFrame(columns=empty_cols)

  pak_keys = _read_reference_list(tags_xlsx, "ПАК")
  vak_keys = _read_reference_list(tags_xlsx, "ВАК")
  long_df = long_df.copy()
  long_df["_key"] = long_df["indicator"].map(_canon)
  mask_pak = long_df["_key"].isin(pak_keys) & ~long_df["_key"].isin(vak_keys)
  mask_vak = long_df["_key"].isin(vak_keys)
  pak_df = long_df[mask_pak].drop(columns="_key").reset_index(drop=True)
  vak_df = long_df[mask_vak].drop(columns="_key").reset_index(drop=True)

  rest = long_df[~mask_pak & ~mask_vak].drop(columns="_key").reset_index(drop=True)
  if not rest.empty:
    log.info("ПАК/ВАК: %d строк не распознаны, отнесены к ПАК.", len(rest))
    pak_df = pd.concat([pak_df, rest], ignore_index=True)

  log.info("Разделение ПАК/ВАК: ПАК=%d строк, ВАК=%d строк",
           len(pak_df), len(vak_df))
  return pak_df, vak_df

# Единая 10-минутная сетка телеметрии
def build_regular_grid(avt: pd.DataFrame, hydro: pd.DataFrame, freq: str = "10min",
                       ffill_limit: int = 3) -> pd.DataFrame:
  # Ресемплинг двух потоков в общую сетку
  def _resample(df: pd.DataFrame, prefix: str) -> pd.DataFrame:
    df = df.set_index("date").sort_index()
    df = df[~df.index.duplicated(keep="last")]
    r = df.resample(freq).mean()
    r.columns = [f"{prefix}{c}" for c in r.columns]
    return r

  avt_r = _resample(avt, "avt_")
  hyd_r = _resample(hydro, "hyd_")

  inter = set(avt_r.columns) & set(hyd_r.columns)
  if inter:
    raise RuntimeError(f"Коллизия имен колонок АВТ/24-2000: {sorted(inter)[:10]}")

  grid = avt_r.join(hyd_r, how="outer")
  grid = grid.ffill(limit=ffill_limit)
  grid.index.name = "timestamp"
  grid = grid.reset_index()
  log.info("Регулярная сетка (%s): %s", freq, grid.shape)
  return grid

# Качество: приоритетное слияние источников
DEFAULT_TOLERANCES = {
    "default": pd.Timedelta(hours=8),
    "sulfur": pd.Timedelta(hours=4),
    "density": pd.Timedelta(hours=4),
    "cloud": pd.Timedelta(hours=24),
    "flash": pd.Timedelta(hours=24),
}

def _tolerance_for(indicator: str) -> pd.Timedelta:
  name = str(indicator).lower()
  for key, tol in DEFAULT_TOLERANCES.items():
    if key != "default" and key in name:
      return tol
  return DEFAULT_TOLERANCES["default"]

@dataclass
class QualityBundle:
  lims: pd.DataFrame = field(default_factory=pd.DataFrame)
  pak: pd.DataFrame = field(default_factory=pd.DataFrame)
  vak: pd.DataFrame = field(default_factory=pd.DataFrame)

def _indicator_match_cols(df: pd.DataFrame) -> pd.DataFrame:
  df = df.copy()
  df["ind_key"] = (df["indicator"].astype(str).str.lower()
                   .str.replace(r"[^\wа-яё]+", "_", regex=True)
                   .str.strip("_"))
  return df

def _priority_resolve(all_q: pd.DataFrame) -> pd.DataFrame:
  # Для каждой пары (timestamp, ind_key) выбирает источник с наивысшим
  # приоритетом (lims=0, pak=1, vak=2)
  frames = []
  for _, sub in all_q.groupby("ind_key", sort=False):
    sub = sub.sort_values(["timestamp", "priority"])
    sub = sub.drop_duplicates(["timestamp", "priority"], keep="last")
    best = sub.sort_values("priority").drop_duplicates("timestamp", keep="first")
    frames.append(best[["timestamp", "ind_key", "value", "source"]])
  if not frames:
    return pd.DataFrame(columns=["timestamp", "ind_key", "value", "source"])
  return pd.concat(frames, ignore_index=True).sort_values("timestamp")

def merge_quality_sources(bundle: QualityBundle) -> pd.DataFrame:
  # Единый ряд качества: ЛИМС > ПАК > ВАК (для каждого ind_key)
  parts = []
  for src_name, df in (("lims", bundle.lims), ("pak", bundle.pak), ("vak", bundle.vak)):
    if df is None or df.empty:
      continue
    d = _indicator_match_cols(df)[["timestamp", "ind_key", "value"]].copy()
    d["source"] = src_name
    d["priority"] = {"lims": 0, "pak": 1, "vak": 2}[src_name]
    parts.append(d)

  if not parts:
    log.warning("Нет ни одного источника качества (ЛИМС/ПАК/ВАК).")
    return pd.DataFrame(columns=["timestamp", "ind_key", "value", "source"])

  all_q = pd.concat(parts, ignore_index=True).sort_values("timestamp")
  merged = _priority_resolve(all_q)
  log.info("Слияние качества: %d строк, %d уникальных ind_key",
           len(merged), merged["ind_key"].nunique())
  return merged

def attach_quality(telemetry: pd.DataFrame, quality: pd.DataFrame) -> pd.DataFrame:
  # Прикрепляет качество (уже с приоритетом) к телеметрии с помощью merge_asof.
  # Добавляет <ind>_value, <ind>_age_min, <ind>_src. NaN сохраняются, нули не
  # подставляются.
  out = telemetry.sort_values("timestamp").copy()
  if quality is None or quality.empty:
    return out

  quality = quality.sort_values("timestamp")

  for ind_key, sub in quality.groupby("ind_key", sort=False):
    sub = sub[["timestamp", "value", "source"]].dropna(subset=["value"])
    if sub.empty:
      continue

    tol = _tolerance_for(ind_key)
    col = re.sub(r"[^\w]+", "_", str(ind_key)).strip("_").lower()
    merged = pd.merge_asof(out[["timestamp"]],
                           sub.rename(columns={"value": f"{col}_value",
                                               "source": f"{col}_src"}),
                           on="timestamp", direction="backward", tolerance=tol)

    # Явно сохраняем NaN: без .values, присваиваем через reindex
    merged = merged.set_index(out.index)
    out[f"{col}_value"] = merged[f"{col}_value"]
    age = (out["timestamp"] - merged["timestamp"]).dt.total_seconds() / 60.0
    out[f"{col}_age_min"] = age
    src = pd.Series([None] * len(out), index=out.index, dtype="object")
    mask = merged[f"{col}_src"].notna().values
    src.loc[mask] = merged[f"{col}_src"].values[mask]
    out[f"{col}_src"] = src

  return out


# Флаги: missing/stale/outlier
def _robust_z(s: pd.Series) -> pd.Series:
  med = s.median()
  mad = (s - med).abs().median()
  if mad == 0 or pd.isna(mad):
    return pd.Series(np.zeros(len(s)), index=s.index)
  return 0.6745*(s - med)/mad


def flag_anomalies(df: pd.DataFrame, numeric_cols: Iterable[str] | None = None,
                   z_thr: float = 6.0, stale_steps: int = 18) -> pd.DataFrame:
  # Проставляет <col>_flag_missing/_stale/_outlier
  df = df.sort_values("timestamp").reset_index(drop=True).copy()
  numeric_cols = list(numeric_cols) if numeric_cols else [c for c in df.columns
    if pd.api.types.is_numeric_dtype(df[c]) and not c.endswith(("_age_min", "_src"))]

  for c in numeric_cols:
    s = df[c]
    df[f"{c}_flag_missing"] = s.isna()
    diff = s.diff().fillna(0)
    unchanged = (diff == 0).astype(int)
    roll = unchanged.rolling(stale_steps, min_periods=stale_steps).sum()
    df[f"{c}_flag_stale"] = (roll >= stale_steps - 1) & s.notna()
    z = _robust_z(s.fillna(s.median()))
    df[f"{c}_flag_outlier"] = (z.abs() > z_thr) & s.notna()

  return df

# Хронологическое разделение
def time_split(df: pd.DataFrame, train_end: str, val_end: str, ts_col: str = "timestamp"):
  # Хронологическое разбиение без перемешивания
  df = df.sort_values(ts_col)
  te, ve = pd.Timestamp(train_end), pd.Timestamp(val_end)
  train = df[df[ts_col] < te].reset_index(drop=True)
  val = df[(df[ts_col] >= te) & (df[ts_col] < ve)].reset_index(drop=True)
  test = df[df[ts_col] >= ve].reset_index(drop=True)
  return train, val, test

# Полный пайплайн
def build_preprocessed_dataset(paths: Paths, freq: str = "10min",
                               train_end: str = "2026-01-01",
                               val_end: str = "2026-05-01") -> dict:
  # 1) Телеметрия
  avt = load_telemetry(paths.avt_tags)
  hyd = load_telemetry(paths.hydro_tags)

  # 2) Справочник КИП
  kip = load_kip_map(paths.tags_xlsx, sheet="КИП")

  # 3) Качество: ЛИМС + ПАК/ВАК
  lims = load_lims(paths.lims_xlsx)
  pak_vak_all = load_pak(paths.pak_xlsx,
                         sheet_aliases=("ПАК", "PAK", "Поточный", "Лист1"),
                         required=False)
  pak, vak = split_pak_vak(pak_vak_all, paths.tags_xlsx)

  # 4) Регулярная сетка телеметрии
  telemetry = build_regular_grid(avt, hyd, freq=freq)

  # 5) Приоритетное слияние качества (ЛИМС > ПАК > ВАК)
  quality = merge_quality_sources(QualityBundle(lims=lims, pak=pak, vak=vak))

  # 6) Прикрепление качества к телеметрии (asof + tolerance)
  enriched = attach_quality(telemetry, quality)

  # 7) Флаги проблем
  enriched = flag_anomalies(enriched)

  # 8) Хронологическое разделение
  train, val, test = time_split(enriched, train_end, val_end)

  log.info("Финал: %s | train=%d, val=%d, test=%d", enriched.shape, len(train),
           len(val), len(test))

  return {"telemetry": telemetry, "lims": lims, "pak": pak, "vak": vak,
          "kip": kip, "quality_merged": quality, "final": enriched,
          "splits": {"train": train, "val": val, "test": test}}

# Экспорт артефактов
SaveFormat = Literal["csv", "json", "both"]

def artifact_root(base: Path | str | None = None) -> Path:
  # Абсолютный корень артефактов
  if base is None:
    env = os.environ.get("NEFTECODE_ARTIFACTS")
    base = Path(env) if env else Path.cwd() / "artifacts"
  root = Path(base).expanduser().resolve()
  root.mkdir(parents=True, exist_ok=True)
  log.info("Артефакты будут сохранены в: %s", root)
  return root

def _json_safe(df: pd.DataFrame) -> list[dict]:
  # DataFrame -> список словарей, пригодных для json.dumps
  d = df.copy()
  for c in d.columns:
    if pd.api.types.is_datetime64_any_dtype(d[c]):
      d[c] = d[c].dt.strftime("%Y-%m-%d %H:%M:%S")
  return json.loads(d.to_json(orient="records", date_format="iso"))

def save_df(df: pd.DataFrame, name: str, root: Path, fmt: SaveFormat = "both",
            also_parquet: bool = False) -> Path:
  # Сохраняет DataFrame в csv/json/parquet
  root.mkdir(parents=True, exist_ok=True)
  written: list[Path] = []

  if fmt in ("csv", "both"):
    csv_path = root/f"{name}.csv"
    df.to_csv(csv_path, index=False, date_format="%Y-%m-%d %H:%M:%S")
    written.append(csv_path)

  if fmt in ("json", "both"):
    json_path = root/f"{name}.json"
    json_path.write_text(json.dumps(_json_safe(df), ensure_ascii=False,
                                    indent=2), encoding="utf-8")
    written.append(json_path)

  if also_parquet:
    try:
      parquet_path = root/f"{name}.parquet"
      df.to_parquet(parquet_path, index=False)
      written.append(parquet_path)
    except Exception as e:
      log.warning("Parquet недоступен (%s); пропускаю.", e)

  main = written[0] if written else (root / f"{name}.csv")
  log.info("Сохранено: %s (%s)", [str(p.name) for p in written], df.shape)
  return main

# Срезы под агентов
QUALITY_INDICATORS = ["sulfur", "d15", "density", "cloud", "flash", "t50",
                      "t90", "t95", "cfpp", "pour", "viscosity", "cetane",
                      "ibp", "ebp", "i250", "i350"]

def build_quality_view(final: pd.DataFrame) -> pd.DataFrame:
  # Для агента качества: timestamp + *_value/*_age_min/*_src/*_flag_*,
  # у которых indicator похож на показатель качества
  cols = ["timestamp"]
  for c in final.columns:
    c_low = c.lower()
    if c_low == "timestamp":
      continue
    if any(k in c_low for k in QUALITY_INDICATORS):
      cols.append(c)
  cols = [c for c in cols if c in final.columns]
  return final[cols].copy()

def build_reliability_view(final: pd.DataFrame) -> pd.DataFrame:
  # Для агента надежности: режимные теги avt_*/hyd_* + все *_flag_*
  keep = ["timestamp"]
  for c in final.columns:
    c_low = c.lower()
    if c_low == "timestamp":
      continue
    if c_low.endswith(("_age_min", "_src")):
      continue
    if c_low.endswith(("_flag_stale", "_flag_missing", "_flag_outlier")):
      keep.append(c)
      continue
    if re.match(r"^(avt|hyd)_[a-z]\d+$", c_low):
      keep.append(c)
  keep = [c for c in keep if c in final.columns]
  return final[keep].copy()

def build_orchestrator_view(final: pd.DataFrame) -> pd.DataFrame:
  # Для оркестратора: timestamp + ключевые технологические теги + все *_value
  preferred = [
      # АВТ
      "avt_t1", "avt_p2", "avt_t6", "avt_t20", "avt_p21", "avt_t33",
      "avt_t48", "avt_p44", "avt_p50", "avt_f7", "avt_f8", "avt_f9",
      "avt_f30", "avt_f32", "avt_f34", "avt_f45", "avt_f16",
      # 24-2000
      "hyd_t5", "hyd_p8", "hyd_f9", "hyd_t11", "hyd_t12", "hyd_t18",
      "hyd_f22", "hyd_t23", "hyd_p24", "hyd_f26",
  ]
  preferred = [c.lower() for c in preferred]
  cols = ["timestamp"] + [c for c in preferred if c in final.columns]
  cols += [c for c in final.columns if c.endswith("_value")]
  cols = list(dict.fromkeys(cols))
  return final[cols].copy()

def export_agent_views(final: pd.DataFrame, root: Path,
                       fmt: SaveFormat = "both") -> dict[str, Path]:
  # Сохраняет три среза + сам final; возвращает {name: path}
  out = {}
  out["final"] = save_df(final, "final", root, fmt=fmt)
  out["view_quality"] = save_df(build_quality_view(final), "view_quality",
                                root, fmt=fmt)
  out["view_reliability"] = save_df(build_reliability_view(final),
                                    "view_reliability", root, fmt=fmt)
  out["view_orchestrator"] = save_df(build_orchestrator_view(final),
                                      "view_orchestrator", root, fmt=fmt)
  return out


def run_processing(
    paths: Paths,
    artifact_dir: Path | str | None = None,
    *,
    fmt: SaveFormat = "csv",
    include_report: bool = False,
) -> tuple[dict, dict[str, Path]]:
  """Запускает общий пайплайн и экспортирует контрактные срезы.

  Эту функцию используют и CLI, и HTTP-загрузка: потребитель всегда получает
  ``final`` и ``view_orchestrator`` из одной и той же предобработки.
  """
  data = build_preprocessed_dataset(paths)
  root = artifact_root(artifact_dir)
  saved: dict[str, Path] = {}
  for name in ("telemetry", "lims", "pak", "vak", "kip", "quality_merged", "final"):
    df = data.get(name)
    if isinstance(df, pd.DataFrame) and not df.empty:
      saved[name] = save_df(df, name, root, fmt=fmt)
  for split_name, df in data["splits"].items():
    if isinstance(df, pd.DataFrame) and not df.empty:
      saved[f"split_{split_name}"] = save_df(df, f"split_{split_name}", root, fmt=fmt)
  saved.update(export_agent_views(data["final"], root, fmt=fmt))

  if include_report:
    plots_dir = root / "plots"
    pngs: list[Path] = []
    try:
      pngs += plot_quality_trends(data["final"], plots_dir)
      pngs.append(plot_missing_map(data["final"], plots_dir))
    except Exception as error:
      log.warning("Не удалось построить графики: %s", error)
    write_html_report(
        root,
        {key: value.shape for key, value in data.items() if isinstance(value, pd.DataFrame)},
        pngs,
    )
  return data, saved

# Графики и HTML-отчет
def plot_quality_trends(final: pd.DataFrame, out_dir: Path) -> list[Path]:
  # По каждому *_value: значение + возраст анализа
  import matplotlib
  matplotlib.use("Agg")
  import matplotlib.pyplot as plt

  out_dir.mkdir(parents=True, exist_ok=True)
  saved: list[Path] = []
  for col in [c for c in final.columns if c.endswith("_value")]:
    base = col[:-len("_value")]
    age_col = f"{base}_age_min"
    fig, ax1 = plt.subplots(figsize=(12, 3.5))
    ax1.plot(final["timestamp"], final[col], color="C0", lw=1)
    ax1.set_ylabel(col, color="C0")
    ax1.tick_params(axis="y", labelcolor="C0")
    if age_col in final.columns:
      ax2 = ax1.twinx()
      ax2.plot(final["timestamp"], final[age_col], color="C1", lw=1, alpha=0.5)
      ax2.set_ylabel("age, min", color="C1")
      ax2.tick_params(axis="y", labelcolor="C1")
    ax1.set_title(f"{col} и возраст анализа")
    fig.tight_layout()
    p = out_dir / f"trend_{base}.png"
    fig.savefig(p, dpi=110)
    plt.close(fig)
    saved.append(p)
  log.info("Графиков построено: %d", len(saved))
  return saved

def plot_missing_map(final: pd.DataFrame, out_dir: Path) -> Path:
  # Карта пропусков: heatmap долей NaN по 6-часовым бакетам
  import matplotlib
  matplotlib.use("Agg")
  import matplotlib.pyplot as plt

  out_dir.mkdir(parents=True, exist_ok=True)
  cols = [c for c in final.columns if not c.endswith(("_age_min", "_src",
                                                      "_flag_stale",
                                                      "_flag_missing",
                                                      "_flag_outlier"))]
  sub = final.set_index("timestamp")[cols].isna().resample("6h").mean()
  fig, ax = plt.subplots(figsize=(14, min(0.25*len(cols)+2, 20)))
  im = ax.imshow(sub.T.values, aspect="auto", cmap="magma", vmin=0, vmax=1)
  ax.set_yticks(range(len(cols)))
  ax.set_yticklabels(cols, fontsize=6)
  step = max(1, len(sub)//10)
  ax.set_xticks(range(0, len(sub), step))
  ax.set_xticklabels([t.strftime("%Y-%m-%d") for t in sub.index[::step]],
                     rotation=45, ha="right", fontsize=7)
  ax.set_title("Доля NaN по 6-часовым бакетам")
  fig.colorbar(im, ax=ax, shrink=0.6)
  fig.tight_layout()
  p = out_dir/"missing_map.png"
  fig.savefig(p, dpi=110)
  plt.close(fig)
  log.info("Карта пропусков: %s", p)
  return p

def write_html_report(root: Path, summary: dict, pngs: list[Path]) -> Path:
  # Сводный HTML с метриками и графиками
  html = ["<html><head><meta charset='utf-8'>",
          "<title>Предобработка — отчёт</title>",
          "<style>body{font-family:sans-serif;max-width:1100px;margin:20px auto}",
          "img{max-width:100%;border:1px solid #ccc;margin:8px 0}",
          "table{border-collapse:collapse}td,th{border:1px solid #ccc;padding:4px 8px}",
          "</style></head><body>",
          "<h1>Предобработка данных — отчёт</h1>",
          "<h2>Сводка</h2><table>",
          "<tr><th>артефакт</th><th>shape</th></tr>"]
  for k, v in summary.items():
    html.append(f"<tr><td>{k}</td><td>{v}</td></tr>")
  html.append("</table><h2>Графики</h2>")
  for p in pngs:
    html.append(f"<h3>{p.name}</h3><img src='plots/{p.name}'>")
  html.append("</body></html>")
  out = root/"report.html"
  out.write_text("\n".join(html), encoding="utf-8")
  log.info("HTML-отчёт: %s", out)
  return out

# Точка входа
if __name__ == "__main__":
  paths = Paths(avt_tags=Path("avt_tags.csv"), hydro_tags=Path("242000_tags.csv"),
                lims_xlsx=Path("ЛИМСы 01.01.2023 - н.в_ (2).xlsx"),
                pak_xlsx=Path("Выгрузка ПАК.xlsx"),
                tags_xlsx=Path("Теги_хакатон.xlsx"))

  # Диагностика листов
  print("=== Диагностика листов ===")
  for p in (paths.pak_xlsx, paths.lims_xlsx, paths.tags_xlsx):
    if p.exists():
      print(f"{p.name} -> {pd.ExcelFile(p).sheet_names}")
    else:
      print(f"{p.name} -> ФАЙЛ НЕ НАЙДЕН")

  # Пайплайн
  data = build_preprocessed_dataset(paths)

  # Корень артефактов
  root = artifact_root()

  # Базовые артефакты
  saved: dict[str, Path] = {}
  for name in ("telemetry", "lims", "pak", "vak", "kip", "quality_merged", "final"):
    df = data.get(name)
    if isinstance(df, pd.DataFrame) and not df.empty:
      saved[name] = save_df(df, name, root)

  # Сплиты
  for split_name, df in data["splits"].items():
    if df is not None and not df.empty:
      saved[f"split_{split_name}"] = save_df(df, f"split_{split_name}", root)

  # Срезы под агентов
  saved.update(export_agent_views(data["final"], root))

  # Графики и HTML-отчет
  plots_dir = root/"plots"
  pngs: list[Path] = []
  try:
    pngs += plot_quality_trends(data["final"], plots_dir)
    pngs.append(plot_missing_map(data["final"], plots_dir))
  except Exception as e:
    log.warning("Не удалось построить графики: %s", e)

  summary = {k: getattr(v, "shape", "—") for k, v in data.items() if isinstance(v, pd.DataFrame)}
  write_html_report(root, summary, pngs)

  # Итоговый отчет в консоль
  print("\n=== Готово ===")
  print("ROOT :", root)
  print("\nАртефакты:")
  for k, p in saved.items():
      print(f"  {k:22s} -> {p}")
  print(f"  {'plots':22s} -> {plots_dir} ({len(pngs)} файлов)")
  print(f"  {'report':22s} -> {root / 'report.html'}")

  print("\nShapes:")
  print("telemetry:", data["telemetry"].shape)
  print("lims:", data["lims"].shape)
  print("pak:", data["pak"].shape)
  print("vak:", data["vak"].shape)
  print("kip:", data["kip"].shape)
  print("quality_merged:", data["quality_merged"].shape)
  print("final:", data["final"].shape)
  print("train/val/test:", len(data["splits"]["train"]), len(data["splits"]["val"]),
       len(data["splits"]["test"]))
