from enum import StrEnum


class ReasonCode(StrEnum):
    RECOMMEND_TOP_RANKED_SAFE_CANDIDATE = "RECOMMEND_TOP_RANKED_SAFE_CANDIDATE"

    KEEP_CURRENT_MODE_SAFE = "KEEP_CURRENT_MODE_SAFE"
    KEEP_NO_FEASIBLE_CHANGE = "KEEP_NO_FEASIBLE_CHANGE"
    KEEP_TOP_CANDIDATE_IS_NO_CHANGE = "KEEP_TOP_CANDIDATE_IS_NO_CHANGE"
    KEEP_CONFIDENCE_BELOW_RECOMMENDATION = "KEEP_CONFIDENCE_BELOW_RECOMMENDATION"
    KEEP_RECOMMENDATION_GUARD = "KEEP_RECOMMENDATION_GUARD"

    REFUSE_CONTRACT_INVALID = "REFUSE_CONTRACT_INVALID"
    REFUSE_COMPONENT_TIMEOUT = "REFUSE_COMPONENT_TIMEOUT"
    REFUSE_COMPONENT_FAILURE = "REFUSE_COMPONENT_FAILURE"
    REFUSE_REQUIRED_QUALITY_MISSING = "REFUSE_REQUIRED_QUALITY_MISSING"
    REFUSE_REQUIRED_RELIABILITY_MISSING = "REFUSE_REQUIRED_RELIABILITY_MISSING"
    REFUSE_LOW_DATA_CONFIDENCE = "REFUSE_LOW_DATA_CONFIDENCE"
    REFUSE_CURRENT_UNSAFE_NO_FEASIBLE = "REFUSE_CURRENT_UNSAFE_NO_FEASIBLE"
    REFUSE_CURRENT_SAFETY_UNKNOWN = "REFUSE_CURRENT_SAFETY_UNKNOWN"
    REFUSE_SCENARIO_INCOMPLETE = "REFUSE_SCENARIO_INCOMPLETE"
    REFUSE_INCONSISTENT_NO_CHANGE = "REFUSE_INCONSISTENT_NO_CHANGE"
    REFUSE_RECOMMENDATION_GUARD = "REFUSE_RECOMMENDATION_GUARD"
